package com.rong.dao;

import com.jfinal.plugin.activerecord.Page;
import com.rong.dao.base.BaseMemorandum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memorandum extends BaseMemorandum<Memorandum> {
	public static final Memorandum dao = new Memorandum().dao();
	
	public static Page<Memorandum> page(int pageNo,int pageSize,Boolean finished,String date,Boolean expir,String startDate){
		String select = "select * ";
		String sqlExceptSelect = "from  memorandum";
		StringBuffer where = new StringBuffer(" where 1=1");
		if (finished != null) {
			where.append(" and finished = " + finished);
		}
		if (date != null && !date.equals("")) {
			where.append(" and DATE_FORMAT(start_date,'%Y-%m') = DATE_FORMAT('"+date+"','%Y-%m')");
		}
		if (expir != null && expir) {
			where.append(" and to_days(now()) >= to_days(expir_date)");
		}
		if (startDate != null && !startDate.equals("")) {
			where.append(" and to_days(start_date) = to_days('"+startDate+"')");
		}
		sqlExceptSelect += where + " order by id desc";
		return dao.paginate(pageNo, pageSize, select,sqlExceptSelect);
	}
	
	public static Integer count(int y,int m,String date){
		if(date==null || date.equals("") ||date.equals("&nbsp;")){
			return 0;
		}
		date = y+"-"+(m+1)+"-"+date;
		String sql = "select count(*) mycount from memorandum where to_days(start_date) = to_days('"+date+"')";
		return dao.findFirst(sql).getInt("mycount");
	}
}
